# Generated by Django 2.0.1 on 2018-01-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0005_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_church', to='main_app.Church')),
            ],
        ),
    ]
