# Generated by Django 2.0.1 on 2018-01-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_person_role'),
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='minister',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minister', to='main_app.Person'),
        ),
    ]
