# Generated by Django 2.0.1 on 2018-01-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20180113_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.BooleanField(default=False)),
                ('choir', models.BooleanField(default=False)),
                ('bells', models.BooleanField(default=False)),
                ('flowers', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('cd', models.BooleanField(default=False)),
                ('winter_heating', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='ServiceReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=50)),
                ('reader', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'verbose_name_plural': 'Service Statuses'},
        ),
        migrations.AddField(
            model_name='wedding',
            name='banns_date',
            field=models.DateField(default='2018-02-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='by_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='dear',
            field=models.CharField(default='Mr', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='mail_title',
            field=models.CharField(default='Mr', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='reading',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='service_reading', to='wedding.ServiceReading'),
            preserve_default=False,
        ),
    ]
