# Generated by Django 2.0.1 on 2018-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_auto_20180114_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.AddField(
            model_name='wedding',
            name='bells',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='cd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='choir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='flowers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='organ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='winter_heating',
            field=models.BooleanField(default=False),
        ),
    ]
