# Generated by Django 2.0.1 on 2018-01-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_auto_20180114_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reading', to='wedding.ServiceReading'),
        ),
    ]
