# Generated by Django 2.0.1 on 2018-01-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20180115_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereadings',
            name='bible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicereadings',
            name='other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
