# Generated by Django 2.0.1 on 2018-01-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_auto_20180115_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='reading',
        ),
        migrations.AddField(
            model_name='servicereadings',
            name='wedding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_reading', to='wedding.Wedding'),
            preserve_default=False,
        ),
    ]
