# Generated by Django 2.0.1 on 2018-01-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20180115_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHymns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hymn', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='wedding',
            name='car_park_attendant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='flowers_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='flowers_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='marches',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='no_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wedding',
            name='office_to_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='order_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='organist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='rehearsal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='rehearsal_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='singing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='verger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='wheelchair_access',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehymns',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_hymn', to='wedding.Wedding'),
        ),
    ]
