# Generated by Django 2.0.1 on 2018-02-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20180130_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceReadings',
            new_name='ServiceReading',
        ),
    ]
