# Generated by Django 2.0.1 on 2018-02-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_auto_20180211_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceHymns',
            new_name='ServiceHymn',
        ),
    ]
