# Generated by Django 2.0.2 on 2018-02-19 12:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180206_2213'),
        ('wedding', '0012_auto_20180211_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churchId', to='main_app.Church')),
            ],
        ),
    ]
