# Generated by Django 2.0.2 on 2018-02-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_churchprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchprice',
            old_name='churchId',
            new_name='church',
        ),
    ]
