# Generated by Django 2.0.2 on 2018-02-19 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_auto_20180219_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='extraPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bylicense', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('Organ', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('Choir', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('bells', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('flowers', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('video', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('cd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('winterHeating', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('verger', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('carParkAttendant', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
            ],
        ),
    ]
