# Generated by Django 2.0.2 on 2018-02-19 13:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0019_auto_20180219_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservices',
            name='name',
            field=models.CharField(choices=[('50', 'By License'), ('100', 'Organ'), ('150', 'Choir'), ('100', 'Bells'), ('200', 'Flowers'), ('500', 'Video'), ('400', 'Cd'), ('1000', 'Winter Heating'), ('300', 'Verger'), ('500', 'Car Park Attendant')], default=Decimal('0.0000'), max_length=100, verbose_name='nombre'),
        ),
    ]
