# Generated by Django 2.0.2 on 2018-02-20 04:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0020_auto_20180219_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservices',
            name='name',
            field=models.CharField(choices=[('By License', '50'), ('Organ', '100'), ('Choir', '150'), ('Bells', '100'), ('Flowers', '200'), ('Video', '500'), ('Cd', '400'), ('Winter Heating', '1000'), ('Verger', '300'), ('Car Park Attendant', '500')], default=Decimal('0.0000'), max_length=100, verbose_name='nombre'),
        ),
    ]
