# Generated by Django 2.0.2 on 2018-02-20 05:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0021_auto_20180220_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservices',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='name',
            field=models.CharField(choices=[('By License', 'By License'), ('Organ', 'Organ'), ('Choir', 'Choir'), ('Bells', 'Bells'), ('Flowers', 'Flowers'), ('Video', 'Video'), ('Cd', 'Cd'), ('Winter Heating', 'Winter Heating'), ('Verger', 'Verger'), ('Car Park Attendant', 'Car Park Attendant')], default=Decimal('0.0000'), max_length=100, verbose_name='Additional Services'),
        ),
    ]
