# Generated by Django 2.0.2 on 2018-02-20 06:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0022_auto_20180220_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservices',
            name='price',
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='banns_current_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='banns_upcoming_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='banns_upcoming_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='statutory_current_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='statutory_upcoming_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='statutory_upcoming_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
