# Generated by Django 2.0.2 on 2018-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0023_auto_20180220_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereading',
            name='other_reader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='bible',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='other_reader',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Reader'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='reader',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bible Reader'),
        ),
    ]
