# Generated by Django 2.0.2 on 2018-02-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0024_auto_20180220_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalservices',
            old_name='banns_current_price',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='additionalservices',
            old_name='banns_upcoming_date',
            new_name='upcoming_date',
        ),
        migrations.RenameField(
            model_name='additionalservices',
            old_name='banns_upcoming_price',
            new_name='upcoming_price',
        ),
        migrations.RemoveField(
            model_name='additionalservices',
            name='statutory_current_price',
        ),
        migrations.RemoveField(
            model_name='additionalservices',
            name='statutory_upcoming_date',
        ),
        migrations.RemoveField(
            model_name='additionalservices',
            name='statutory_upcoming_price',
        ),
    ]
