# Generated by Django 2.0.2 on 2018-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0025_auto_20180220_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='Hymn1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='Hymn2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='Hymn3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='Hymn4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='Hymn5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='Hymn6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
