# Generated by Django 2.0.2 on 2018-02-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0026_auto_20180220_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='date_amount_paid',
            field=models.TextField(blank=True, null=True, verbose_name='Dates and Amounts Paid'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='total_paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
