# Generated by Django 2.0.2 on 2018-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0027_auto_20180221_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='banns_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='decree_abs_seen',
            field=models.BooleanField(default=False, verbose_name='Decree Abs Seen'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='evidence_filed',
            field=models.BooleanField(default=False, verbose_name='Evidence Filed'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='first_visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='second_visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='third_visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
