# Generated by Django 2.0.2 on 2018-02-23 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0028_auto_20180221_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='additionalServices',
        ),
        migrations.AddField(
            model_name='wedding',
            name='by_license_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
