# Generated by Django 2.0.2 on 2018-02-23 13:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0030_auto_20180223_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='church_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
