# Generated by Django 2.0.2 on 2018-02-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0031_wedding_church_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='Hymn1',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Hymn2',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Hymn3',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Hymn4',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Hymn5',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Hymn6',
        ),
        migrations.AlterField(
            model_name='wedding',
            name='banns_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
