# Generated by Django 2.0.1 on 2018-01-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180110_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
