# Generated by Django 2.0.1 on 2018-01-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180129_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age_at_wedding',
            field=models.IntegerField(default=10, max_length=2),
            preserve_default=False,
        ),
    ]
