# Generated by Django 2.0.1 on 2018-01-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_person_age_at_wedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proofs',
            options={'verbose_name_plural': 'Proofs'},
        ),
    ]
