# Generated by Django 2.0.1 on 2018-01-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180129_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_at_wedding',
            field=models.IntegerField(),
        ),
    ]
