# Generated by Django 2.0.1 on 2018-01-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180129_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minister_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ministers',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AlterField(
            model_name='person',
            name='age_at_wedding',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
