# Generated by Django 2.0.1 on 2018-02-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_person_wedding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('Groom', 'Groom'), ('Bride', 'Bride')], max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='wedding_id',
            field=models.IntegerField(blank=True),
        ),
    ]
